### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by irodeanu** [howljs/rn-card-scanner#1]
It's not working on android, not recognize card data

**Comment by liptonzuma** [comment]
Same here

**Comment by govarthananve** [comment]
Android getting 
<img width="438" alt="Screenshot 2022-10-18 at 12 34 24 PM" src="https://user-images.githubusercontent.com/17062177/196359849-d30c296d-04d6-4101-b4bc-18f80bbe58fa.png">

**Comment by howljs** [comment]
@irodeanu @liptonzuma maybe your credit card is not supported. I using on my app, it worked normally
@govarthananve you need install library and re-install app

**Comment by govarthananve** [comment]
@howljs Thanks for the update actually I after linking to the npm it's working fine
