### ISSUE TITLE
Scan not working as expected Android 

### ISSUE THREAD

**Issue by govarthananve** [howljs/rn-card-scanner#4]
If I scan the 3d printed credit card number it's working fine.
Sample card
![visa-card-business-chip-724x456](https://user-images.githubusercontent.com/17062177/196432243-77d950d6-32c4-48e7-bc55-1cb9ed3be255.jpeg)

If I use some 2d printed credit card number the scan is not working.
Sample card
![preview](https://user-images.githubusercontent.com/17062177/196432213-186a3694-ba20-4c1a-8e9d-68b7a22b87c4.png)

Any reason?

**Comment by FeMaffezzolli** [comment]
We are having the same problem.

**Comment by howljs** [comment]
Currently, native library only supports 3d printed credit card numbers. I will try to find a new native library
