### ISSUE TITLE
Iphone app getting crash if Camera open

### ISSUE THREAD

**Issue by govarthananve** [howljs/rn-card-scanner#5]
Without getting any error the app getting crashes if I used iPhone to scan 
Reproduce scenario 
First, open the scanner and allow the camera to close without scanning anything to kill the app.
The second time open the app and open the scanner its not show the camera after some time(3  to 4 sec) its getting crashes

**Comment by govarthananve** [comment]
@howljs Any update on this issue

**Comment by howljs** [comment]
Can you share your code?
On my device (iPhone 14 Pro Max), the scanner working normally

**Comment by govarthananve** [comment]
`import CardScanner from 'rn-card-scanner';

import moment from "moment";
`
`<CardScanner

                  style={{

                    flexGrow: 1,

                    overflow: 'hidden',

                    marginBottom: 20,

                    backgroundColor: '#CCCCCC',

                  }}

                  didCardScan={(card) => {

                    console.log('Card info: ', card);

                    const getEYears = moment(card.expiryYear, "YY");

                    const expiryYears = getEYears.format("YYYY");

                    console.log('Card info: expiryYears', expiryYears);

                    // let expiryMonth =

                    //   card.expiryMonth < 10

                    //     ? '0' + card.expiryMonth.toString()

                    //     : card.expiryMonth.toString();



                    let card_ExpiryDate =

                    card.expiryMonth.toString() + '/' + expiryYears.toString();

                    console.log('Card info: card_ExpiryDate', card_ExpiryDate);

                    // Card Validation Methods Calls

                    this.creditCardTextChange(card.cardNumber);

                    this.handleChange(card_ExpiryDate);

                    // this.setHighlightedCardtype(card?.cardType);

                    this.setState({isScanCardEnable: false});

                  }}

                />`

**Comment by VladyslavKondratiev** [comment]
@govarthananve be sure that you provided `NSCameraUsageDescription` in Info.plist
